### PR TITLE
PSG-2286: add type parameter to createMagicLink type

### PR DESCRIPTION
**Pull request by apobletts**
Do not merge until backend PR is merged.

Adds a type parameter to the magic link creation.

### CODE REVIEW

**Comment by bertrmz** [comment]
This will also require a version bump of the value here: https://github.com/passageidentity/passage-go/blob/5273206c99f669f9c43057b5776b7565b24c1635/version.txt#L1

**Comment by bertrmz** [comment]
This will also require a version bump of the value here: https://github.com/passageidentity/passage-go/blob/5273206c99f669f9c43057b5776b7565b24c1635/version.txt#L1C2-L1C2

**Comment by duanebester** [comment]
> This will also require a version bump of the value here:
> 
> https://github.com/passageidentity/passage-go/blob/5273206c99f669f9c43057b5776b7565b24c1635/version.txt#L1

@bertrmz thinking 1.4.1 or 1.5.0?

**Comment by duanebester** [comment]
@bertrmz @himichaelroberts 
thoughts on
```go
type MagicLinkType string

const (
	LoginType            MagicLinkType = "login"
	VerifyIdentifierType MagicLinkType = "verify_identifier"
)

type CreateMagicLinkBody struct {
	UserID        string      `json:"user_id"`
	Email         string      `json:"email"`
	Phone         string      `json:"phone"`
	Channel       ChannelType `json:"channel"`
	Send          bool        `json:"send"`
	MagicLinkPath string      `json:"magic_link_path"`
	RedirectURL   string      `json:"redirect_url"`
	TTL           int         `json:"ttl"`
	Language      string      `json:"language"`
	Type          MagicLinkType      `json:"type,omitempty"`
}
```

**Comment by danilo-kaltner** [comment]
> > This will also require a version bump of the value here:
> > https://github.com/passageidentity/passage-go/blob/5273206c99f669f9c43057b5776b7565b24c1635/version.txt#L1
> 
> @bertrmz thinking 1.4.1 or 1.5.0?

More like 1.5.0 since this is adding a new field

**Review by danilo-kaltner — APPROVED** [review]

**Pull request merged**
